spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j2ee_Assignment03
    username: root
    password: 7400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true